version: "3.9" 
name: ${COMPOSE_PROJECT_NAME:-postgres}
services: 
  database: 
    container_name: ${CONTAINER_NAME:?container name is not defined...} 
    build: 
      context: . 
      target: database
      dockerfile_inline: | 
        FROM postgres:16.0 as database
        RUN localedef -i es_ES -c -f UTF-8 -A /usr/share/locale/locale.alias es_ES.UTF-8
        ENV LANG es_ES.utf8
    env_file: .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backups:/backups
    extra_hosts:
      - host.docker.internal:host-gateway