name: ${CONTAINER_NAME:?container name is not defined...}-postgres
services: 
  base: &base
    container_name: ${CONTAINER_NAME:?container name is not defined...}-db
    build: 
      context: . 
      target: database
      dockerfile_inline: | 
        FROM postgres:${POSTGRES_VERSION} as database
        RUN localedef -i es_AR -c -f UTF-8 -A /usr/share/locale/locale.alias es_AR.UTF-8
        ENV LANG es_AR.utf8
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./docker/volumes/data:/var/lib/postgresql/data
      - ./docker/volumes/backups:/backups
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    <<: *base

  dev:
    <<: *base
    env_file:
      - ./.env
